using LIOSCare.ClinicPortal.Web.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LIOSCare.ClinicPortal.Web.Data.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("202606160010_IdentityTenantPortalSafe")]
public partial class IdentityTenantPortalSafe : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
        CREATE EXTENSION IF NOT EXISTS pgcrypto;
        CREATE SCHEMA IF NOT EXISTS portal;

        CREATE TABLE IF NOT EXISTS "AspNetRoles" (
            "Id" uuid NOT NULL PRIMARY KEY,
            "Name" varchar(256),
            "NormalizedName" varchar(256),
            "ConcurrencyStamp" text,
            "Description" varchar(255)
        );
        ALTER TABLE "AspNetRoles" ADD COLUMN IF NOT EXISTS "Description" varchar(255);

        CREATE TABLE IF NOT EXISTS portal.clinics_hospitals (
            "Id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
            "Name" varchar(160) NOT NULL,
            "Type" varchar(30) NOT NULL,
            "Status" varchar(30) NOT NULL,
            "ContactEmail" varchar(255) NOT NULL,
            "ContactPhone" varchar(40) NOT NULL,
            "City" varchar(120) NOT NULL,
            "Country" varchar(120) NOT NULL,
            "Address" text NOT NULL,
            "AdminUserId" uuid,
            "CreatedAt" timestamptz DEFAULT now() NOT NULL,
            "UpdatedAt" timestamptz DEFAULT now() NOT NULL
        );

        CREATE TABLE IF NOT EXISTS "AspNetUsers" (
            "Id" uuid NOT NULL PRIMARY KEY,
            "UserName" varchar(256),
            "NormalizedUserName" varchar(256),
            "Email" varchar(256),
            "NormalizedEmail" varchar(256),
            "EmailConfirmed" boolean NOT NULL DEFAULT false,
            "PasswordHash" text,
            "SecurityStamp" text,
            "ConcurrencyStamp" text,
            "PhoneNumber" text,
            "PhoneNumberConfirmed" boolean NOT NULL DEFAULT false,
            "TwoFactorEnabled" boolean NOT NULL DEFAULT false,
            "LockoutEnd" timestamptz,
            "LockoutEnabled" boolean NOT NULL DEFAULT false,
            "AccessFailedCount" integer NOT NULL DEFAULT 0,
            "FullName" varchar(160) NOT NULL DEFAULT '',
            "Status" varchar(30) NOT NULL DEFAULT 'Active',
            "ClinicHospitalId" uuid,
            "CreatedAt" timestamptz DEFAULT now() NOT NULL,
            "UpdatedAt" timestamptz DEFAULT now() NOT NULL,
            "DeactivatedAt" timestamptz
        );

        ALTER TABLE "AspNetUsers" ADD COLUMN IF NOT EXISTS "FullName" varchar(160) NOT NULL DEFAULT '';
        ALTER TABLE "AspNetUsers" ADD COLUMN IF NOT EXISTS "Status" varchar(30) NOT NULL DEFAULT 'Active';
        ALTER TABLE "AspNetUsers" ADD COLUMN IF NOT EXISTS "ClinicHospitalId" uuid;
        ALTER TABLE "AspNetUsers" ADD COLUMN IF NOT EXISTS "CreatedAt" timestamptz DEFAULT now() NOT NULL;
        ALTER TABLE "AspNetUsers" ADD COLUMN IF NOT EXISTS "UpdatedAt" timestamptz DEFAULT now() NOT NULL;
        ALTER TABLE "AspNetUsers" ADD COLUMN IF NOT EXISTS "DeactivatedAt" timestamptz;

        CREATE TABLE IF NOT EXISTS "AspNetUserRoles" ("UserId" uuid NOT NULL, "RoleId" uuid NOT NULL, PRIMARY KEY ("UserId", "RoleId"));
        CREATE TABLE IF NOT EXISTS "AspNetUserClaims" ("Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "UserId" uuid NOT NULL, "ClaimType" text, "ClaimValue" text);
        CREATE TABLE IF NOT EXISTS "AspNetRoleClaims" ("Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "RoleId" uuid NOT NULL, "ClaimType" text, "ClaimValue" text);
        CREATE TABLE IF NOT EXISTS "AspNetUserLogins" ("LoginProvider" varchar(128) NOT NULL, "ProviderKey" varchar(128) NOT NULL, "ProviderDisplayName" text, "UserId" uuid NOT NULL, PRIMARY KEY ("LoginProvider", "ProviderKey"));
        CREATE TABLE IF NOT EXISTS "AspNetUserTokens" ("UserId" uuid NOT NULL, "LoginProvider" varchar(128) NOT NULL, "Name" varchar(128) NOT NULL, "Value" text, PRIMARY KEY ("UserId", "LoginProvider", "Name"));

        CREATE TABLE IF NOT EXISTS portal.patient_accounts (
            "Id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
            "AnonymousCode" varchar(80) NOT NULL,
            "AnonymousDisplayName" varchar(120) NOT NULL,
            "UserPortalEmail" varchar(255),
            "CreatedAt" timestamptz DEFAULT now() NOT NULL
        );
        CREATE UNIQUE INDEX IF NOT EXISTS "IX_patient_accounts_AnonymousCode" ON portal.patient_accounts("AnonymousCode");

        CREATE TABLE IF NOT EXISTS portal.service_tiers (
            "Id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
            "Name" varchar(40) NOT NULL,
            "DurationMinutes" integer NOT NULL,
            "Price" numeric(18,2) NOT NULL,
            "Currency" varchar(3) NOT NULL,
            "ServiceType" varchar(30) NOT NULL DEFAULT 'Chat',
            "IsActive" boolean NOT NULL,
            "SortOrder" integer NOT NULL
        );
        ALTER TABLE portal.service_tiers ADD COLUMN IF NOT EXISTS "ServiceType" varchar(30) NOT NULL DEFAULT 'Chat';
        CREATE INDEX IF NOT EXISTS "IX_service_tiers_active_sort" ON portal.service_tiers("IsActive", "SortOrder");

        CREATE TABLE IF NOT EXISTS portal.doctor_profiles (
            "Id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
            "UserId" uuid NOT NULL,
            "ClinicId" uuid,
            "DisplayName" varchar(140) NOT NULL,
            "Specializations" text[] NOT NULL DEFAULT ARRAY[]::text[],
            "YearsExperience" integer NOT NULL,
            "LicenseNumber" varchar(80) NOT NULL,
            "Bio" text NOT NULL,
            "IsAvailable" boolean NOT NULL,
            "MaxConcurrentSessions" integer DEFAULT 3 NOT NULL,
            "Status" varchar(30) NOT NULL,
            "ChatSessionPrice" numeric(18,2) DEFAULT 0 NOT NULL,
            "OnlineConsultationPrice" numeric(18,2) DEFAULT 0 NOT NULL,
            "ChatSessionMinutes" integer DEFAULT 30 NOT NULL,
            "OnlineConsultationMinutes" integer DEFAULT 40 NOT NULL,
            "Currency" varchar(3) DEFAULT 'USD' NOT NULL,
            "WorkingDays" text[] NOT NULL DEFAULT ARRAY[]::text[],
            "WorkStartTime" time,
            "WorkEndTime" time,
            "CreatedAt" timestamptz DEFAULT now() NOT NULL,
            "UpdatedAt" timestamptz DEFAULT now() NOT NULL
        );
        ALTER TABLE portal.doctor_profiles ADD COLUMN IF NOT EXISTS "ChatSessionPrice" numeric(18,2) DEFAULT 0 NOT NULL;
        ALTER TABLE portal.doctor_profiles ADD COLUMN IF NOT EXISTS "OnlineConsultationPrice" numeric(18,2) DEFAULT 0 NOT NULL;
        ALTER TABLE portal.doctor_profiles ADD COLUMN IF NOT EXISTS "ChatSessionMinutes" integer DEFAULT 30 NOT NULL;
        ALTER TABLE portal.doctor_profiles ADD COLUMN IF NOT EXISTS "OnlineConsultationMinutes" integer DEFAULT 40 NOT NULL;
        ALTER TABLE portal.doctor_profiles ADD COLUMN IF NOT EXISTS "Currency" varchar(3) DEFAULT 'USD' NOT NULL;
        ALTER TABLE portal.doctor_profiles ADD COLUMN IF NOT EXISTS "WorkingDays" text[] NOT NULL DEFAULT ARRAY[]::text[];
        ALTER TABLE portal.doctor_profiles ADD COLUMN IF NOT EXISTS "WorkStartTime" time;
        ALTER TABLE portal.doctor_profiles ADD COLUMN IF NOT EXISTS "WorkEndTime" time;
        CREATE INDEX IF NOT EXISTS "IX_doctor_profiles_clinic_status" ON portal.doctor_profiles("ClinicId", "Status");
        CREATE UNIQUE INDEX IF NOT EXISTS "IX_doctor_profiles_user" ON portal.doctor_profiles("UserId");

        CREATE TABLE IF NOT EXISTS portal.chat_session_jobs (
            "Id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
            "PatientId" uuid NOT NULL,
            "PreferredDoctorId" uuid,
            "ClinicId" uuid,
            "ServiceTierId" uuid NOT NULL,
            "JobType" varchar(30) DEFAULT 'QuickChat' NOT NULL,
            "Status" varchar(30) NOT NULL,
            "PatientNotePublic" text NOT NULL,
            "OfferExpiresAt" timestamptz NOT NULL,
            "AcceptedByDoctorId" uuid,
            "AcceptedAt" timestamptz,
            "RejectedAt" timestamptz,
            "RejectedReason" text,
            "CreatedAt" timestamptz DEFAULT now() NOT NULL,
            "UpdatedAt" timestamptz DEFAULT now() NOT NULL
        );
        CREATE INDEX IF NOT EXISTS "IX_jobs_clinic_status_expiry" ON portal.chat_session_jobs("ClinicId", "Status", "OfferExpiresAt");
        CREATE INDEX IF NOT EXISTS "IX_jobs_doctor_status" ON portal.chat_session_jobs("PreferredDoctorId", "Status");

        CREATE TABLE IF NOT EXISTS portal.chat_sessions (
            "Id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
            "JobId" uuid NOT NULL,
            "DoctorId" uuid NOT NULL,
            "PatientId" uuid NOT NULL,
            "ServiceTierId" uuid NOT NULL,
            "Status" varchar(30) NOT NULL,
            "DurationMinutes" integer NOT NULL,
            "ScheduledStartAt" timestamptz NOT NULL,
            "ActualStartedAt" timestamptz,
            "AutoCloseAt" timestamptz NOT NULL,
            "ClosedAt" timestamptz,
            "CloseReason" text,
            "CreatedAt" timestamptz DEFAULT now() NOT NULL,
            "UpdatedAt" timestamptz DEFAULT now() NOT NULL
        );
        CREATE INDEX IF NOT EXISTS "IX_chat_sessions_doctor_status" ON portal.chat_sessions("DoctorId", "Status", "AutoCloseAt");

        CREATE TABLE IF NOT EXISTS portal.chat_messages (
            "Id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
            "ChatSessionId" uuid NOT NULL,
            "SenderType" varchar(20) NOT NULL,
            "SenderUserId" uuid,
            "Body" text NOT NULL,
            "CreatedAt" timestamptz DEFAULT now() NOT NULL
        );
        CREATE INDEX IF NOT EXISTS "IX_chat_messages_session_created" ON portal.chat_messages("ChatSessionId", "CreatedAt");

        CREATE TABLE IF NOT EXISTS portal.reschedule_requests (
            "Id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
            "ChatSessionId" uuid NOT NULL,
            "PatientId" uuid NOT NULL,
            "RequestedStartAt" timestamptz NOT NULL,
            "Reason" text NOT NULL,
            "Status" varchar(30) NOT NULL,
            "RespondedByDoctorId" uuid,
            "RespondedAt" timestamptz,
            "CreatedAt" timestamptz DEFAULT now() NOT NULL
        );
        CREATE INDEX IF NOT EXISTS "IX_reschedule_session_status" ON portal.reschedule_requests("ChatSessionId", "Status");

        CREATE TABLE IF NOT EXISTS portal.notifications (
            "Id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
            "RecipientUserId" uuid NOT NULL,
            "Type" varchar(120) NOT NULL,
            "Title" varchar(180) NOT NULL,
            "Body" text NOT NULL,
            "EntityType" varchar(80) NOT NULL,
            "EntityId" uuid,
            "ReadAt" timestamptz,
            "CreatedAt" timestamptz DEFAULT now() NOT NULL
        );
        CREATE INDEX IF NOT EXISTS "IX_notifications_recipient" ON portal.notifications("RecipientUserId", "ReadAt", "CreatedAt");

        CREATE TABLE IF NOT EXISTS portal.session_reports (
            "Id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
            "ChatSessionId" uuid NOT NULL,
            "DoctorId" uuid NOT NULL,
            "AnonymousPatientLabel" varchar(120) NOT NULL,
            "SessionDate" date NOT NULL,
            "MoodBefore" integer NOT NULL,
            "MoodAfter" integer NOT NULL,
            "GoalsCompleted" integer NOT NULL,
            "GoalsTotal" integer NOT NULL,
            "ProgressNotes" text NOT NULL,
            "TechniquesUsed" text[] NOT NULL DEFAULT ARRAY[]::text[],
            "NextSteps" text,
            "CreatedAt" timestamptz DEFAULT now() NOT NULL,
            "UpdatedAt" timestamptz DEFAULT now() NOT NULL,
            "LockedAt" timestamptz NOT NULL
        );
        CREATE INDEX IF NOT EXISTS "IX_reports_doctor_date" ON portal.session_reports("DoctorId", "SessionDate");

        CREATE UNIQUE INDEX IF NOT EXISTS "RoleNameIndex" ON "AspNetRoles"("NormalizedName");
        CREATE INDEX IF NOT EXISTS "EmailIndex" ON "AspNetUsers"("NormalizedEmail");
        CREATE UNIQUE INDEX IF NOT EXISTS "UserNameIndex" ON "AspNetUsers"("NormalizedUserName");
        CREATE INDEX IF NOT EXISTS "IX_AspNetUsers_ClinicHospitalId" ON "AspNetUsers"("ClinicHospitalId");
        CREATE INDEX IF NOT EXISTS "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles"("RoleId");
        CREATE INDEX IF NOT EXISTS "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims"("UserId");
        CREATE INDEX IF NOT EXISTS "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims"("RoleId");
        CREATE INDEX IF NOT EXISTS "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins"("UserId");
        CREATE INDEX IF NOT EXISTS "IX_AspNetUserTokens_UserId" ON "AspNetUserTokens"("UserId");
        """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
        DROP TABLE IF EXISTS portal.session_reports CASCADE;
        DROP TABLE IF EXISTS portal.reschedule_requests CASCADE;
        DROP TABLE IF EXISTS portal.chat_messages CASCADE;
        DROP TABLE IF EXISTS portal.chat_sessions CASCADE;
        DROP TABLE IF EXISTS portal.chat_session_jobs CASCADE;
        DROP TABLE IF EXISTS portal.doctor_profiles CASCADE;
        DROP TABLE IF EXISTS portal.service_tiers CASCADE;
        DROP TABLE IF EXISTS portal.patient_accounts CASCADE;
        DROP TABLE IF EXISTS portal.notifications CASCADE;
        DROP TABLE IF EXISTS "AspNetUserTokens" CASCADE;
        DROP TABLE IF EXISTS "AspNetUserLogins" CASCADE;
        DROP TABLE IF EXISTS "AspNetUserClaims" CASCADE;
        DROP TABLE IF EXISTS "AspNetRoleClaims" CASCADE;
        DROP TABLE IF EXISTS "AspNetUserRoles" CASCADE;
        DROP TABLE IF EXISTS "AspNetUsers" CASCADE;
        DROP TABLE IF EXISTS "AspNetRoles" CASCADE;
        DROP TABLE IF EXISTS portal.clinics_hospitals CASCADE;
        """);
    }
}
