// <auto-generated />
using System;
using LIOSCare.ClinicPortal.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LIOSCare.ClinicPortal.Web.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LIOSCare.ClinicPortal.Web.Data.Entities.ApplicationRole", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("text");
                b.Property<string>("Description").HasMaxLength(255).HasColumnType("character varying(255)");
                b.Property<string>("Name").HasMaxLength(256).HasColumnType("character varying(256)");
                b.Property<string>("NormalizedName").HasMaxLength(256).HasColumnType("character varying(256)");
                b.HasKey("Id");
                b.HasIndex("NormalizedName").IsUnique().HasDatabaseName("RoleNameIndex");
                b.ToTable("AspNetRoles");
            });

            modelBuilder.Entity("LIOSCare.ClinicPortal.Web.Data.Entities.ApplicationUser", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<int>("AccessFailedCount").HasColumnType("integer");
                b.Property<Guid?>("ClinicHospitalId").HasColumnType("uuid");
                b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("text");
                b.Property<DateTimeOffset>("CreatedAt").ValueGeneratedOnAdd().HasColumnType("timestamp with time zone").HasDefaultValueSql("now()");
                b.Property<DateTimeOffset?>("DeactivatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Email").HasMaxLength(256).HasColumnType("character varying(256)");
                b.Property<bool>("EmailConfirmed").HasColumnType("boolean");
                b.Property<string>("FullName").IsRequired().ValueGeneratedOnAdd().HasMaxLength(160).HasColumnType("character varying(160)").HasDefaultValue("");
                b.Property<bool>("LockoutEnabled").HasColumnType("boolean");
                b.Property<DateTimeOffset?>("LockoutEnd").HasColumnType("timestamp with time zone");
                b.Property<string>("NormalizedEmail").HasMaxLength(256).HasColumnType("character varying(256)");
                b.Property<string>("NormalizedUserName").HasMaxLength(256).HasColumnType("character varying(256)");
                b.Property<string>("PasswordHash").HasColumnType("text");
                b.Property<string>("PhoneNumber").HasColumnType("text");
                b.Property<bool>("PhoneNumberConfirmed").HasColumnType("boolean");
                b.Property<string>("SecurityStamp").HasColumnType("text");
                b.Property<string>("Status").IsRequired().ValueGeneratedOnAdd().HasMaxLength(30).HasColumnType("character varying(30)").HasDefaultValue("Active");
                b.Property<bool>("TwoFactorEnabled").HasColumnType("boolean");
                b.Property<DateTimeOffset>("UpdatedAt").ValueGeneratedOnAdd().HasColumnType("timestamp with time zone").HasDefaultValueSql("now()");
                b.Property<string>("UserName").HasMaxLength(256).HasColumnType("character varying(256)");
                b.HasKey("Id");
                b.HasIndex("ClinicHospitalId").HasDatabaseName("IX_AspNetUsers_ClinicHospitalId");
                b.HasIndex("NormalizedEmail").HasDatabaseName("EmailIndex");
                b.HasIndex("NormalizedUserName").IsUnique().HasDatabaseName("UserNameIndex");
                b.ToTable("AspNetUsers");
            });

            modelBuilder.Entity("LIOSCare.ClinicPortal.Web.Data.Entities.ClinicHospital", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasDefaultValueSql("gen_random_uuid()");
                b.Property<string>("Address").IsRequired().HasColumnType("text");
                b.Property<Guid?>("AdminUserId").HasColumnType("uuid");
                b.Property<string>("City").IsRequired().HasMaxLength(120).HasColumnType("character varying(120)");
                b.Property<string>("ContactEmail").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)");
                b.Property<string>("ContactPhone").IsRequired().HasMaxLength(40).HasColumnType("character varying(40)");
                b.Property<string>("Country").IsRequired().HasMaxLength(120).HasColumnType("character varying(120)");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Name").IsRequired().HasMaxLength(160).HasColumnType("character varying(160)");
                b.Property<string>("Status").IsRequired().HasMaxLength(30).HasColumnType("character varying(30)");
                b.Property<string>("Type").IsRequired().HasMaxLength(30).HasColumnType("character varying(30)");
                b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.HasIndex("AdminUserId").HasDatabaseName("IX_clinics_hospitals_AdminUserId");
                b.HasIndex("Status").HasDatabaseName("IX_clinics_hospitals_Status");
                b.ToTable("clinics_hospitals", "portal");
            });

            modelBuilder.Entity("LIOSCare.ClinicPortal.Web.Data.Entities.ChatMessage", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasDefaultValueSql("gen_random_uuid()");
                b.Property<string>("Body").IsRequired().HasColumnType("text");
                b.Property<Guid>("ChatSessionId").HasColumnType("uuid");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("SenderType").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
                b.Property<Guid?>("SenderUserId").HasColumnType("uuid");
                b.HasKey("Id");
                b.HasIndex("ChatSessionId", "CreatedAt").HasDatabaseName("IX_chat_messages_ChatSessionId_CreatedAt");
                b.ToTable("chat_messages", "portal");
            });

            modelBuilder.Entity("LIOSCare.ClinicPortal.Web.Data.Entities.ChatSession", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasDefaultValueSql("gen_random_uuid()");
                b.Property<DateTimeOffset?>("ActualStartedAt").HasColumnType("timestamp with time zone");
                b.Property<DateTimeOffset>("AutoCloseAt").HasColumnType("timestamp with time zone");
                b.Property<string>("CloseReason").HasColumnType("text");
                b.Property<DateTimeOffset?>("ClosedAt").HasColumnType("timestamp with time zone");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid>("DoctorId").HasColumnType("uuid");
                b.Property<int>("DurationMinutes").HasColumnType("integer");
                b.Property<Guid>("JobId").HasColumnType("uuid");
                b.Property<Guid>("PatientId").HasColumnType("uuid");
                b.Property<DateTimeOffset>("ScheduledStartAt").HasColumnType("timestamp with time zone");
                b.Property<Guid>("ServiceTierId").HasColumnType("uuid");
                b.Property<string>("Status").IsRequired().HasMaxLength(30).HasColumnType("character varying(30)");
                b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.HasIndex("PatientId").HasDatabaseName("IX_chat_sessions_PatientId");
                b.HasIndex("JobId").HasDatabaseName("IX_chat_sessions_JobId");
                b.HasIndex("ServiceTierId").HasDatabaseName("IX_chat_sessions_ServiceTierId");
                b.HasIndex("DoctorId", "Status", "AutoCloseAt").HasDatabaseName("IX_chat_sessions_DoctorId_Status_AutoCloseAt");
                b.ToTable("chat_sessions", "portal");
            });

            modelBuilder.Entity("LIOSCare.ClinicPortal.Web.Data.Entities.ChatSessionJob", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasDefaultValueSql("gen_random_uuid()");
                b.Property<DateTimeOffset?>("AcceptedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid?>("AcceptedByDoctorId").HasColumnType("uuid");
                b.Property<Guid?>("ClinicId").HasColumnType("uuid");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("JobType").IsRequired().HasMaxLength(30).HasColumnType("character varying(30)");
                b.Property<DateTimeOffset>("OfferExpiresAt").HasColumnType("timestamp with time zone");
                b.Property<Guid>("PatientId").HasColumnType("uuid");
                b.Property<string>("PatientNotePublic").IsRequired().HasColumnType("text");
                b.Property<Guid?>("PreferredDoctorId").HasColumnType("uuid");
                b.Property<DateTimeOffset?>("RejectedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("RejectedReason").HasColumnType("text");
                b.Property<Guid>("ServiceTierId").HasColumnType("uuid");
                b.Property<string>("Status").IsRequired().HasMaxLength(30).HasColumnType("character varying(30)");
                b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.HasIndex("PatientId").HasDatabaseName("IX_chat_session_jobs_PatientId");
                b.HasIndex("ServiceTierId").HasDatabaseName("IX_chat_session_jobs_ServiceTierId");
                b.HasIndex("PreferredDoctorId", "Status").HasDatabaseName("IX_chat_session_jobs_PreferredDoctorId_Status");
                b.HasIndex("ClinicId", "Status", "OfferExpiresAt").HasDatabaseName("IX_chat_session_jobs_ClinicId_Status_OfferExpiresAt");
                b.ToTable("chat_session_jobs", "portal");
            });

            modelBuilder.Entity("LIOSCare.ClinicPortal.Web.Data.Entities.DoctorProfile", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasDefaultValueSql("gen_random_uuid()");
                b.Property<string>("Bio").IsRequired().HasColumnType("text");
                b.Property<decimal>("ChatSessionPrice").HasColumnType("numeric(18,2)");
                b.Property<int>("ChatSessionMinutes").HasColumnType("integer");
                b.Property<Guid?>("ClinicId").HasColumnType("uuid");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Currency").IsRequired().HasMaxLength(3).HasColumnType("character varying(3)");
                b.Property<string>("DisplayName").IsRequired().HasMaxLength(140).HasColumnType("character varying(140)");
                b.Property<bool>("IsAvailable").HasColumnType("boolean");
                b.Property<string>("LicenseNumber").IsRequired().HasMaxLength(80).HasColumnType("character varying(80)");
                b.Property<int>("MaxConcurrentSessions").HasColumnType("integer");
                b.Property<decimal>("OnlineConsultationPrice").HasColumnType("numeric(18,2)");
                b.Property<int>("OnlineConsultationMinutes").HasColumnType("integer");
                b.Property<string[]>("Specializations").IsRequired().HasColumnType("text[]");
                b.Property<string>("Status").IsRequired().HasMaxLength(30).HasColumnType("character varying(30)");
                b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid>("UserId").HasColumnType("uuid");
                b.Property<TimeOnly?>("WorkEndTime").HasColumnType("time without time zone");
                b.Property<string[]>("WorkingDays").IsRequired().HasColumnType("text[]");
                b.Property<TimeOnly?>("WorkStartTime").HasColumnType("time without time zone");
                b.Property<int>("YearsExperience").HasColumnType("integer");
                b.HasKey("Id");
                b.HasIndex("UserId").IsUnique().HasDatabaseName("IX_doctor_profiles_UserId");
                b.HasIndex("ClinicId", "Status").HasDatabaseName("IX_doctor_profiles_ClinicId_Status");
                b.ToTable("doctor_profiles", "portal");
            });

            modelBuilder.Entity("LIOSCare.ClinicPortal.Web.Data.Entities.NotificationItem", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasDefaultValueSql("gen_random_uuid()");
                b.Property<string>("Body").IsRequired().HasColumnType("text");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid?>("EntityId").HasColumnType("uuid");
                b.Property<string>("EntityType").IsRequired().HasMaxLength(80).HasColumnType("character varying(80)");
                b.Property<DateTimeOffset?>("ReadAt").HasColumnType("timestamp with time zone");
                b.Property<Guid>("RecipientUserId").HasColumnType("uuid");
                b.Property<string>("Title").IsRequired().HasMaxLength(180).HasColumnType("character varying(180)");
                b.Property<string>("Type").IsRequired().HasMaxLength(120).HasColumnType("character varying(120)");
                b.HasKey("Id");
                b.HasIndex("RecipientUserId", "ReadAt", "CreatedAt").HasDatabaseName("IX_notifications_RecipientUserId_ReadAt_CreatedAt");
                b.ToTable("notifications", "portal");
            });

            modelBuilder.Entity("LIOSCare.ClinicPortal.Web.Data.Entities.PatientAccount", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasDefaultValueSql("gen_random_uuid()");
                b.Property<string>("AnonymousCode").IsRequired().HasMaxLength(80).HasColumnType("character varying(80)");
                b.Property<string>("AnonymousDisplayName").IsRequired().HasMaxLength(120).HasColumnType("character varying(120)");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("UserPortalEmail").HasMaxLength(255).HasColumnType("character varying(255)");
                b.HasKey("Id");
                b.HasIndex("AnonymousCode").IsUnique().HasDatabaseName("IX_patient_accounts_AnonymousCode");
                b.ToTable("patient_accounts", "portal");
            });

            modelBuilder.Entity("LIOSCare.ClinicPortal.Web.Data.Entities.RescheduleRequest", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasDefaultValueSql("gen_random_uuid()");
                b.Property<Guid>("ChatSessionId").HasColumnType("uuid");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid>("PatientId").HasColumnType("uuid");
                b.Property<string>("Reason").IsRequired().HasColumnType("text");
                b.Property<DateTimeOffset>("RequestedStartAt").HasColumnType("timestamp with time zone");
                b.Property<DateTimeOffset?>("RespondedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid?>("RespondedByDoctorId").HasColumnType("uuid");
                b.Property<string>("Status").IsRequired().HasMaxLength(30).HasColumnType("character varying(30)");
                b.HasKey("Id");
                b.HasIndex("PatientId").HasDatabaseName("IX_reschedule_requests_PatientId");
                b.HasIndex("ChatSessionId", "Status").HasDatabaseName("IX_reschedule_requests_ChatSessionId_Status");
                b.ToTable("reschedule_requests", "portal");
            });

            modelBuilder.Entity("LIOSCare.ClinicPortal.Web.Data.Entities.ServiceTier", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasDefaultValueSql("gen_random_uuid()");
                b.Property<string>("Currency").IsRequired().HasMaxLength(3).HasColumnType("character varying(3)");
                b.Property<int>("DurationMinutes").HasColumnType("integer");
                b.Property<bool>("IsActive").HasColumnType("boolean");
                b.Property<string>("Name").IsRequired().HasMaxLength(40).HasColumnType("character varying(40)");
                b.Property<decimal>("Price").HasColumnType("numeric(18,2)");
                b.Property<string>("ServiceType").IsRequired().HasMaxLength(30).HasColumnType("character varying(30)");
                b.Property<int>("SortOrder").HasColumnType("integer");
                b.HasKey("Id");
                b.HasIndex("IsActive", "SortOrder").HasDatabaseName("IX_service_tiers_IsActive_SortOrder");
                b.ToTable("service_tiers", "portal");
            });

            modelBuilder.Entity("LIOSCare.ClinicPortal.Web.Data.Entities.SessionReport", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasDefaultValueSql("gen_random_uuid()");
                b.Property<string>("AnonymousPatientLabel").IsRequired().HasMaxLength(120).HasColumnType("character varying(120)");
                b.Property<Guid>("ChatSessionId").HasColumnType("uuid");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid>("DoctorId").HasColumnType("uuid");
                b.Property<int>("GoalsCompleted").HasColumnType("integer");
                b.Property<int>("GoalsTotal").HasColumnType("integer");
                b.Property<DateTimeOffset>("LockedAt").HasColumnType("timestamp with time zone");
                b.Property<int>("MoodAfter").HasColumnType("integer");
                b.Property<int>("MoodBefore").HasColumnType("integer");
                b.Property<string>("NextSteps").HasColumnType("text");
                b.Property<string>("ProgressNotes").IsRequired().HasColumnType("text");
                b.Property<DateOnly>("SessionDate").HasColumnType("date");
                b.Property<string[]>("TechniquesUsed").IsRequired().HasColumnType("text[]");
                b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.HasIndex("ChatSessionId").HasDatabaseName("IX_session_reports_ChatSessionId");
                b.HasIndex("DoctorId", "SessionDate").HasDatabaseName("IX_session_reports_DoctorId_SessionDate");
                b.ToTable("session_reports", "portal");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<string>("ClaimType").HasColumnType("text");
                b.Property<string>("ClaimValue").HasColumnType("text");
                b.Property<Guid>("RoleId").HasColumnType("uuid");
                b.HasKey("Id");
                b.HasIndex("RoleId").HasDatabaseName("IX_AspNetRoleClaims_RoleId");
                b.ToTable("AspNetRoleClaims");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<string>("ClaimType").HasColumnType("text");
                b.Property<string>("ClaimValue").HasColumnType("text");
                b.Property<Guid>("UserId").HasColumnType("uuid");
                b.HasKey("Id");
                b.HasIndex("UserId").HasDatabaseName("IX_AspNetUserClaims_UserId");
                b.ToTable("AspNetUserClaims");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
            {
                b.Property<string>("LoginProvider").HasColumnType("text");
                b.Property<string>("ProviderKey").HasColumnType("text");
                b.Property<string>("ProviderDisplayName").HasColumnType("text");
                b.Property<Guid>("UserId").HasColumnType("uuid");
                b.HasKey("LoginProvider", "ProviderKey");
                b.HasIndex("UserId").HasDatabaseName("IX_AspNetUserLogins_UserId");
                b.ToTable("AspNetUserLogins");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
            {
                b.Property<Guid>("UserId").HasColumnType("uuid");
                b.Property<Guid>("RoleId").HasColumnType("uuid");
                b.HasKey("UserId", "RoleId");
                b.HasIndex("RoleId").HasDatabaseName("IX_AspNetUserRoles_RoleId");
                b.ToTable("AspNetUserRoles");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
            {
                b.Property<Guid>("UserId").HasColumnType("uuid");
                b.Property<string>("LoginProvider").HasColumnType("text");
                b.Property<string>("Name").HasColumnType("text");
                b.Property<string>("Value").HasColumnType("text");
                b.HasKey("UserId", "LoginProvider", "Name");
                b.ToTable("AspNetUserTokens");
            });

            modelBuilder.Entity("LIOSCare.ClinicPortal.Web.Data.Entities.ApplicationUser", b =>
            {
                b.HasOne("LIOSCare.ClinicPortal.Web.Data.Entities.ClinicHospital", "ClinicHospital")
                    .WithMany().HasForeignKey("ClinicHospitalId").OnDelete(DeleteBehavior.Restrict);
                b.Navigation("ClinicHospital");
            });

            modelBuilder.Entity("LIOSCare.ClinicPortal.Web.Data.Entities.ChatMessage", b =>
            {
                b.HasOne("LIOSCare.ClinicPortal.Web.Data.Entities.ChatSession", "ChatSession")
                    .WithMany().HasForeignKey("ChatSessionId").OnDelete(DeleteBehavior.Cascade);
                b.Navigation("ChatSession");
            });

            modelBuilder.Entity("LIOSCare.ClinicPortal.Web.Data.Entities.ChatSession", b =>
            {
                b.HasOne("LIOSCare.ClinicPortal.Web.Data.Entities.ChatSessionJob", "Job")
                    .WithMany().HasForeignKey("JobId").OnDelete(DeleteBehavior.Restrict);
                b.HasOne("LIOSCare.ClinicPortal.Web.Data.Entities.DoctorProfile", "Doctor")
                    .WithMany().HasForeignKey("DoctorId").OnDelete(DeleteBehavior.Restrict);
                b.HasOne("LIOSCare.ClinicPortal.Web.Data.Entities.PatientAccount", "Patient")
                    .WithMany().HasForeignKey("PatientId").OnDelete(DeleteBehavior.Restrict);
                b.HasOne("LIOSCare.ClinicPortal.Web.Data.Entities.ServiceTier", "ServiceTier")
                    .WithMany().HasForeignKey("ServiceTierId").OnDelete(DeleteBehavior.Restrict);
                b.Navigation("Doctor"); b.Navigation("Job"); b.Navigation("Patient"); b.Navigation("ServiceTier");
            });

            modelBuilder.Entity("LIOSCare.ClinicPortal.Web.Data.Entities.ChatSessionJob", b =>
            {
                b.HasOne("LIOSCare.ClinicPortal.Web.Data.Entities.PatientAccount", "Patient")
                    .WithMany().HasForeignKey("PatientId").OnDelete(DeleteBehavior.Restrict);
                b.HasOne("LIOSCare.ClinicPortal.Web.Data.Entities.ServiceTier", "ServiceTier")
                    .WithMany().HasForeignKey("ServiceTierId").OnDelete(DeleteBehavior.Restrict);
                b.Navigation("Patient"); b.Navigation("ServiceTier");
            });

            modelBuilder.Entity("LIOSCare.ClinicPortal.Web.Data.Entities.DoctorProfile", b =>
            {
                b.HasOne("LIOSCare.ClinicPortal.Web.Data.Entities.ApplicationUser", "User")
                    .WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Restrict);
                b.HasOne("LIOSCare.ClinicPortal.Web.Data.Entities.ClinicHospital", "Clinic")
                    .WithMany().HasForeignKey("ClinicId").OnDelete(DeleteBehavior.Restrict);
                b.Navigation("Clinic"); b.Navigation("User");
            });

            modelBuilder.Entity("LIOSCare.ClinicPortal.Web.Data.Entities.RescheduleRequest", b =>
            {
                b.HasOne("LIOSCare.ClinicPortal.Web.Data.Entities.ChatSession", "ChatSession")
                    .WithMany().HasForeignKey("ChatSessionId").OnDelete(DeleteBehavior.Cascade);
                b.HasOne("LIOSCare.ClinicPortal.Web.Data.Entities.PatientAccount", "Patient")
                    .WithMany().HasForeignKey("PatientId").OnDelete(DeleteBehavior.Cascade);
                b.Navigation("ChatSession"); b.Navigation("Patient");
            });

            modelBuilder.Entity("LIOSCare.ClinicPortal.Web.Data.Entities.SessionReport", b =>
            {
                b.HasOne("LIOSCare.ClinicPortal.Web.Data.Entities.ChatSession", "ChatSession")
                    .WithMany().HasForeignKey("ChatSessionId").OnDelete(DeleteBehavior.Cascade);
                b.HasOne("LIOSCare.ClinicPortal.Web.Data.Entities.DoctorProfile", "Doctor")
                    .WithMany().HasForeignKey("DoctorId").OnDelete(DeleteBehavior.Cascade);
                b.Navigation("ChatSession"); b.Navigation("Doctor");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
            {
                b.HasOne("LIOSCare.ClinicPortal.Web.Data.Entities.ApplicationRole", null)
                    .WithMany().HasForeignKey("RoleId").OnDelete(DeleteBehavior.Cascade);
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
            {
                b.HasOne("LIOSCare.ClinicPortal.Web.Data.Entities.ApplicationUser", null)
                    .WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade);
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
            {
                b.HasOne("LIOSCare.ClinicPortal.Web.Data.Entities.ApplicationUser", null)
                    .WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade);
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
            {
                b.HasOne("LIOSCare.ClinicPortal.Web.Data.Entities.ApplicationRole", null)
                    .WithMany().HasForeignKey("RoleId").OnDelete(DeleteBehavior.Cascade);
                b.HasOne("LIOSCare.ClinicPortal.Web.Data.Entities.ApplicationUser", null)
                    .WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade);
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
            {
                b.HasOne("LIOSCare.ClinicPortal.Web.Data.Entities.ApplicationUser", null)
                    .WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade);
            });
#pragma warning restore 612, 618
        }
    }
}
